package com.recaudia.provisioning;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/** Creates the complete tenant schema in a freshly created PostgreSQL database. */
@Component
public class TenantSchemaInitializer {

    public void initialize(JdbcTemplate jdbc) {
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS empresas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                razon_social VARCHAR(255) NOT NULL UNIQUE,
                ruc VARCHAR(20) NOT NULL UNIQUE,
                dominio VARCHAR(255) UNIQUE,
                activa BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS usuarios (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL UNIQUE,
                password_hash VARCHAR(255) NOT NULL,
                rol VARCHAR(50) NOT NULL,
                activo BOOLEAN NOT NULL DEFAULT TRUE,
                empresa_id BIGINT NOT NULL REFERENCES empresas(id),
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS cuentas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                codigo_cliente VARCHAR(255) NOT NULL,
                razon_social VARCHAR(255) NOT NULL,
                ruc VARCHAR(20),
                email_contacto VARCHAR(255),
                telefono_whats_app VARCHAR(255),
                estado VARCHAR(50) NOT NULL,
                empresa_id BIGINT NOT NULL REFERENCES empresas(id),
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS servicios (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                codigo VARCHAR(255) NOT NULL,
                nombre VARCHAR(255) NOT NULL,
                descripcion VARCHAR(255),
                empresa_id BIGINT REFERENCES empresas(id),
                activo BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS servicios_contratados (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cuenta_id BIGINT NOT NULL REFERENCES cuentas(id),
                servicio_id BIGINT NOT NULL REFERENCES servicios(id),
                fecha_inicio DATE,
                fecha_fin DATE,
                tarifa_mensual NUMERIC(12,2),
                activo BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS facturas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                numero_factura VARCHAR(255) NOT NULL,
                fecha_emision DATE NOT NULL,
                fecha_vencimiento DATE,
                monto_total NUMERIC(14,2) NOT NULL,
                monto_pagado NUMERIC(14,2) NOT NULL DEFAULT 0,
                estado VARCHAR(50) NOT NULL,
                cuenta_id BIGINT NOT NULL REFERENCES cuentas(id),
                empresa_id BIGINT NOT NULL REFERENCES empresas(id),
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS pagos (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                monto NUMERIC(14,2) NOT NULL,
                fecha_pago TIMESTAMP NOT NULL,
                medio_pago VARCHAR(255),
                referencia VARCHAR(255),
                factura_id BIGINT NOT NULL REFERENCES facturas(id),
                empresa_id BIGINT NOT NULL REFERENCES empresas(id),
                created_at TIMESTAMP NOT NULL
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS notas_de_credito (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                numero VARCHAR(255) NOT NULL,
                monto NUMERIC(14,2) NOT NULL,
                motivo VARCHAR(255),
                fecha DATE NOT NULL,
                factura_id BIGINT NOT NULL REFERENCES facturas(id),
                empresa_id BIGINT NOT NULL REFERENCES empresas(id),
                created_at TIMESTAMP NOT NULL
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS alertas (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                titulo VARCHAR(255) NOT NULL,
                descripcion TEXT,
                tipo VARCHAR(50) NOT NULL,
                estado VARCHAR(50) NOT NULL,
                factura_id BIGINT UNIQUE REFERENCES facturas(id),
                empresa_id BIGINT NOT NULL REFERENCES empresas(id),
                fecha_creacion TIMESTAMP NOT NULL,
                fecha_resolucion TIMESTAMP
            )
            """);

        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS alerta_revisores (
                alerta_id BIGINT NOT NULL REFERENCES alertas(id) ON DELETE CASCADE,
                usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                PRIMARY KEY (alerta_id, usuario_id)
            )
            """);

        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_usuarios_empresa ON usuarios(empresa_id)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_cuentas_empresa ON cuentas(empresa_id)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_facturas_empresa ON facturas(empresa_id)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_facturas_cuenta ON facturas(cuenta_id)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_pagos_empresa ON pagos(empresa_id)");
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_alertas_empresa ON alertas(empresa_id)");
    }
}
